// disasm.go — Bytecode disassembler for V8Go.
//
// Implements the "Loop-to-Spec" cycle from gojs.md Section 4:
// enables comparison of V8Go bytecode against V8 Ignition --print-bytecode output.
package js

import (
	"fmt"
	"strings"
)

// Disassemble parses, compiles, and prints the bytecode for a JavaScript program.
// Returns the formatted bytecode listing, matching V8 Ignition style.
func (vm *VM) Disassemble(src string) string {
	tokens := NewLexer(src).Tokenize()
	prog, errs := NewParser(tokens).Parse()
	if len(errs) > 0 {
		return "Parse errors: " + strings.Join(errs, "; ")
	}

	bf := Compile(prog)
	return DisassembleFunction(bf)
}

// DisassembleFunction returns a formatted bytecode listing for a compiled function.
func DisassembleFunction(bf *BytecodeFunction) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("[generated bytecode for function: %s]\n", bf.Name))
	sb.WriteString(fmt.Sprintf("Parameter count: %d\n", bf.NumParams))
	sb.WriteString(fmt.Sprintf("Register count: %d\n", bf.NumRegisters))
	sb.WriteString(fmt.Sprintf("Frame size: %d bytes\n", bf.NumRegisters*8))

	// Constant pool.
	sb.WriteString("\nConstant pool:\n")
	for i, c := range bf.Constants {
		sb.WriteString(fmt.Sprintf("  [%d] %s\n", i, formatConstant(c)))
	}

	// Captured variables.
	if len(bf.Captured) > 0 {
		sb.WriteString("\nCaptured variables:\n")
		for _, name := range bf.Captured {
			sb.WriteString(fmt.Sprintf("  %s\n", name))
		}
	}

	// Instructions.
	sb.WriteString("\nBytecode:\n")
	handlers := make([]string, 0)
	for pc, instr := range bf.Instructions {
		handlers = append(handlers, formatInstruction(pc, instr, bf))
	}
	sb.WriteString(strings.Join(handlers, "\n"))
	sb.WriteString("\n")

	return sb.String()
}

func formatConstant(c JSValue) string {
	switch c.Tag {
	case TagNumber:
		return fmt.Sprintf("Number: %v", c.NumVal)
	case TagString:
		return fmt.Sprintf("String: %q", c.StrVal)
	case TagBoolean:
		return fmt.Sprintf("Boolean: %v", c.BoolVal)
	case TagUndefined:
		return "Undefined"
	case TagNull:
		return "Null"
	case TagObject:
		if c.ObjVal != nil && c.ObjVal.ConstructorName == "Function" {
			return fmt.Sprintf("Function: %s", c.ObjVal.ToString())
		}
		return "Object"
	case TagSymbol:
		return fmt.Sprintf("Symbol: %s", c.StrVal)
	}
	return "<unknown>"
}

func formatInstruction(pc int, instr Instruction, bf *BytecodeFunction) string {
	opName := instr.Op.String()
	a, b, c := instr.OperandA, instr.OperandB, instr.OperandC

	var parts []string
	parts = append(parts, fmt.Sprintf("%4d", pc))
	parts = append(parts, opName)

	switch instr.Op {
	case OpLdaConstant:
		parts = append(parts, fmt.Sprintf("<%d>", a))
		if int(a) < len(bf.Constants) {
			parts = append(parts, fmt.Sprintf("; %s", formatConstant(bf.Constants[a])))
		}
	case OpStar:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpLdar:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpMov:
		parts = append(parts, fmt.Sprintf("r%d, r%d", a, b))
	case OpAdd, OpSub, OpMul, OpDiv, OpMod, OpExp,
		OpEq, OpNotEq, OpStrictEq, OpStrictNotEq,
		OpLessThan, OpGreaterThan, OpLessEq, OpGreaterEq,
		OpLogicalAnd, OpLogicalOr,
		OpBitwiseAnd, OpBitwiseOr, OpBitwiseXor,
		OpShiftLeft, OpShiftRight, OpShiftRightZero,
		OpInstanceof, OpIn:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpCall0, OpCall1, OpCall2:
		parts = append(parts, fmt.Sprintf("r%d, r%d", a, b))
	case OpCall:
		parts = append(parts, fmt.Sprintf("r%d, r%d, r%d", a, b, c))
	case OpJump, OpJumpIfFalse, OpJumpIfTrue, OpJumpIfToBooleanTrue, OpJumpIfToBooleanFalse:
		parts = append(parts, fmt.Sprintf("%d", a))
		parts = append(parts, fmt.Sprintf("(to pc=%d)", a))
	case OpLdaNamedProperty, OpStaNamedProperty:
		parts = append(parts, fmt.Sprintf("r%d", a))
		if int(a) < len(bf.Constants) {
			parts = append(parts, fmt.Sprintf("; %s", formatConstant(bf.Constants[a])))
		}
	case OpLdaKeyedProperty, OpStaKeyedProperty:
		parts = append(parts, fmt.Sprintf("r%d, r%d", a, b))
	case OpLdaGlobal, OpStaGlobal:
		parts = append(parts, fmt.Sprintf("<%d>", a))
		if int(a) < len(bf.Constants) {
			parts = append(parts, fmt.Sprintf("; name: %q", bf.Constants[a].ToString()))
		}
	case OpLdaGlobalSlot, OpStaGlobalSlot:
		parts = append(parts, fmt.Sprintf("slot:%d", a))
		if int(a) < len(bf.GlobalSlots) {
			parts = append(parts, fmt.Sprintf("; name: %q", bf.GlobalSlots[a]))
		}
	case OpLdaLocal, OpStaLocal:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpDup:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpThrowConstAssignment:
		parts = append(parts, fmt.Sprintf("k%d", a))
	case OpLdaCaptured:
		parts = append(parts, fmt.Sprintf("r%d", a))
		if int(a) < len(bf.Captured) {
			parts = append(parts, fmt.Sprintf("; captured: %s", bf.Captured[a]))
		}
	case OpForInSetup:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpForInNext:
		parts = append(parts, fmt.Sprintf("r%d", a))
	case OpThrow:
		// No explicit operands; value is in acc.
	case OpSetTryHandler:
		parts = append(parts, fmt.Sprintf("%d", a))
		parts = append(parts, "(handler PC)")
	case OpClearTryHandler:
		// No operands.
	case OpDelete:
		parts = append(parts, fmt.Sprintf("r%d", a))
		if int(a) < len(bf.Constants) {
			parts = append(parts, fmt.Sprintf("; prop: %q", bf.Constants[a].ToString()))
		}
	case OpDeleteKeyed:
		parts = append(parts, fmt.Sprintf("r%d, r%d", a, b))
	}

	line := strings.Join(parts, " ")
	// Pad to align comments.
	if len(line) < 30 {
		line += strings.Repeat(" ", 30-len(line))
	}
	return line
}
