package idl

import (
"fmt"
"strings"
)

// GenerateGo produces Go wrapper code from an IDL Interface.
func GenerateGo(iface *Interface) string {
var b strings.Builder

b.WriteString("// Code generated by idl codegen; DO NOT EDIT.\n\n")
b.WriteString("package bindings\n\n")
b.WriteString("import \"github.com/lucasdss/v8go/pkg/dom\"\n\n")

b.WriteString(fmt.Sprintf("type %sWrapper struct {\n", iface.Name))
b.WriteString("elem *dom.Element\n")
b.WriteString("}\n\n")

b.WriteString(fmt.Sprintf("func New%sWrapper(elem *dom.Element) *%sWrapper {\n", iface.Name, iface.Name))
b.WriteString(fmt.Sprintf("return &%sWrapper{elem: elem}\n", iface.Name))
b.WriteString("}\n\n")

b.WriteString(fmt.Sprintf("func (w *%sWrapper) Element() *dom.Element { return w.elem }\n\n", iface.Name))

for _, attr := range iface.Attributes {
goType := idlToGoType(attr.Type)
getterName := "Get" + strings.ToUpper(attr.Name[:1]) + attr.Name[1:]
if !attr.ReadOnly {
setterName := "Set" + strings.ToUpper(attr.Name[:1]) + attr.Name[1:]
b.WriteString(fmt.Sprintf("func (w *%sWrapper) %s(val %s) {\n", iface.Name, setterName, goType))
if goType == "string" {
b.WriteString(fmt.Sprintf("w.elem.SetAttribute(%q, val)\n", attr.Name))
} else {
b.WriteString(fmt.Sprintf("w.elem.SetAttribute(%q, fmt.Sprint(val))\n", attr.Name))
}
b.WriteString("}\n\n")
}
b.WriteString(fmt.Sprintf("func (w *%sWrapper) %s() %s {\n", iface.Name, getterName, goType))
if goType == "string" {
b.WriteString(fmt.Sprintf("return w.elem.GetAttribute(%q)\n", attr.Name))
} else if goType == "bool" {
b.WriteString(fmt.Sprintf("return w.elem.HasAttribute(%q)\n", attr.Name))
} else {
b.WriteString(fmt.Sprintf("return w.elem.GetAttribute(%q)\n", attr.Name))
}
b.WriteString("}\n\n")
}

for _, op := range iface.Operations {
retType := idlToGoType(op.ReturnType)
args := make([]string, len(op.Args))
for i, a := range op.Args {
args[i] = fmt.Sprintf("%s %s", a.Name, idlToGoType(a.Type))
}
b.WriteString(fmt.Sprintf("func (w *%sWrapper) %s(%s) %s {\n",
iface.Name, op.Name, strings.Join(args, ", "), retType))
if retType == "string" {
b.WriteString("return \"\"\n")
}
b.WriteString("}\n\n")
}

return b.String()
}

func idlToGoType(idlType string) string {
switch idlType {
case "DOMString", "USVString", "ByteString":
return "string"
case "boolean":
return "bool"
case "double", "float":
return "float64"
case "long", "short", "unsigned":
return "int"
case "void":
return ""
default:
return "string"
}
}
