package dom

import (
	"fmt"
	"reflect"
	"strings"
)

// ----------------------------- Event -----------------------------------------
//
// Event represents a DOM event as defined in the WHATWG DOM Standard § 3.1.
// It carries the event type, target, propagation flags, and optional data.

// EventPhase indicates which phase of event propagation is active.
type EventPhase int

const (
	// NonePhase is the default.
	NonePhase EventPhase = 0
	// CapturingPhase is the capture phase (target → root).
	CapturingPhase EventPhase = 1
	// AtTarget is when the event is at the target.
	AtTarget EventPhase = 2
	// BubblingPhase is the bubble phase (target → ancestors).
	BubblingPhase EventPhase = 3
)

// Event represents a DOM event.
// See DOM Standard § 3.1.
type Event struct {
	// Type is the event type string (e.g., "click", "load", "DOMContentLoaded").
	Type string
	// Target is the event target to which the event was originally dispatched.
	Target EventTarget
	// CurrentTarget is the event target whose event listener is currently
	// being invoked.
	CurrentTarget EventTarget
	// EventPhase indicates which phase of event flow is being processed.
	EventPhase EventPhase
	// Bubbles is true if the event bubbles up through the DOM.
	Bubbles bool
	// Cancelable is true if the event's default action can be prevented.
	Cancelable bool
	// DefaultPrevented is true if preventDefault() was called.
	DefaultPrevented bool
	// IsTrusted is true if the event was generated by the user agent
	// (as opposed to script-created events).
	IsTrusted bool
	// Data holds event-specific data (key code, mouse position, etc.).
	Data map[string]interface{}
	// stopPropagation is set internally when stopPropagation() is called.
	stopPropagation bool
	// stopImmediatePropagation is set internally when stopImmediatePropagation()
	// is called.
	stopImmediatePropagation bool
}

// NewEvent creates a new Event with the given type and event init dict.
// See DOM Standard § 3.1 "Creating events".
func NewEvent(eventType string, bubbles, cancelable bool) *Event {
	return &Event{
		Type:       eventType,
		Bubbles:    bubbles,
		Cancelable: cancelable,
		IsTrusted:  true,
		Data:       make(map[string]interface{}),
	}
}

// StopPropagation prevents further propagation of the event during the current
// event flow (capture, target, bubble).
func (e *Event) StopPropagation() {
	e.stopPropagation = true
}

// StopImmediatePropagation prevents other listeners on the same target from
// being called, in addition to stopping propagation.
func (e *Event) StopImmediatePropagation() {
	e.stopImmediatePropagation = true
	e.stopPropagation = true
}

// PreventDefault cancels the event's default action if Cancelable is true.
func (e *Event) PreventDefault() {
	if e.Cancelable {
		e.DefaultPrevented = true
	}
}

// IsPropagationStopped reports whether stopPropagation was called.
func (e *Event) IsPropagationStopped() bool {
	return e.stopPropagation
}

// IsImmediatePropagationStopped reports whether stopImmediatePropagation
// was called.
func (e *Event) IsImmediatePropagationStopped() bool {
	return e.stopImmediatePropagation
}

// String implements fmt.Stringer.
func (e *Event) String() string {
	return fmt.Sprintf("Event{type=%q, target=%v, bubbles=%v}", e.Type, e.Target, e.Bubbles)
}

// ----------------------------- EventListener ----------------------------------

// EventListener is a callback function that handles a DOM event.
type EventListener func(event *Event)

// ----------------------------- EventTarget -----------------------------------

// EventTarget is the interface implemented by objects that can receive events
// and have listeners for them (DOM Nodes, Window, etc.).
// See DOM Standard § 3.6.
type EventTarget interface {
	// AddEventListener registers an event listener on this target.
	AddEventListener(eventType string, listener EventListener, options ...bool)
	// RemoveEventListener removes an event listener from this target.
	RemoveEventListener(eventType string, listener EventListener)
	// DispatchEvent dispatches an event to this target and processes the
	// event flow (capture → target → bubble).
	DispatchEvent(event *Event) bool
	// listenerEntry returns the internal listener list.
	listenerEntry() *listenerList
}

// listenerEntry is a named record of a registered event listener.
type listenerEntry struct {
	Type     string
	Listener EventListener
	Capture  bool // true for capture-phase listeners
	Once     bool // true for one-shot listeners (auto-remove after invocation)
}

// listenerList holds listeners per event type.
type listenerList struct {
	entries []listenerEntry
}

// ----------------------------- Node EventTarget implementation ----------------

// listeners is embedded in Node via a pointer so that nodes without any event
// listeners don't incur memory overhead.
var _ EventTarget = (*Node)(nil)

// AddEventListener registers an event listener on this node.
// The optional bool parameters set capture and once flags.
func (n *Node) AddEventListener(eventType string, listener EventListener, options ...bool) {
	eventType = strings.ToLower(eventType)
	capture := false
	once := false
	if len(options) > 0 {
		capture = options[0]
	}
	if len(options) > 1 {
		once = options[1]
	}

	le := n.listenerEntry()
	le.entries = append(le.entries, listenerEntry{
		Type:     eventType,
		Listener: listener,
		Capture:  capture,
		Once:     once,
	})
}

// RemoveEventListener removes a previously registered event listener.
// Both type and function reference must match.
func (n *Node) RemoveEventListener(eventType string, listener EventListener) {
	eventType = strings.ToLower(eventType)
	le := n.listenerEntry()
	if le == nil {
		return
	}
	for i, entry := range le.entries {
		// Compare function pointers — in Go, function values are comparable.
		if entry.Type == eventType && funcPtrEqual(entry.Listener, listener) {
			le.entries = append(le.entries[:i], le.entries[i+1:]...)
			return
		}
	}
}

// DispatchEvent dispatches an event to this node and processes the event flow:
// capture → target → bubble (if Bubbles is true).
// Returns false if preventDefault() was called and Cancelable is true.
// See DOM Standard § 3.6.
func (n *Node) DispatchEvent(event *Event) bool {
	if event == nil {
		return true
	}

	event.Target = n

	// Build the propagation chain from root to target (capture path).
	var path []*Node
	for p := n; p != nil; p = p.ParentNode() {
		path = append([]*Node{p}, path...)
	}

	// 1. Capture phase: root → target, invoking capture listeners.
	event.EventPhase = CapturingPhase
	for _, node := range path[:len(path)-1] {
		if event.IsPropagationStopped() {
			break
		}
		event.CurrentTarget = node
		node.invokeListeners(event, true)
	}

	// 2. Target phase.
	if !event.IsPropagationStopped() {
		event.EventPhase = AtTarget
		event.CurrentTarget = n
		n.invokeListeners(event, false) // non-capture listeners at target
	}

	// 3. Bubble phase: target → root, invoking non-capture listeners.
	if event.Bubbles && !event.IsPropagationStopped() {
		event.EventPhase = BubblingPhase
		for i := len(path) - 2; i >= 0; i-- {
			if event.IsPropagationStopped() {
				break
			}
			event.CurrentTarget = path[i]
			path[i].invokeListeners(event, false)
		}
	}

	return !event.DefaultPrevented
}

// listenerEntry returns the node's listener list, creating it lazily.
func (n *Node) listenerEntry() *listenerList {
	if n.listeners == nil {
		n.listeners = &listenerList{}
	}
	return n.listeners
}

// invokeListeners calls all matching event listeners on this node.
// If capture is true, only capture-phase listeners are invoked;
// otherwise, only non-capture listeners are invoked.
func (n *Node) invokeListeners(event *Event, capture bool) {
	le := n.listeners
	if le == nil {
		return
	}

	// Snapshot the list to avoid issues with mutation during iteration.
	entries := make([]listenerEntry, len(le.entries))
	copy(entries, le.entries)

	var remaining []listenerEntry
	for _, entry := range entries {
		if entry.Type != event.Type {
			remaining = append(remaining, entry)
			continue
		}
		if entry.Capture != capture {
			remaining = append(remaining, entry)
			continue
		}

		// Invoke listener.
		entry.Listener(event)

		if event.IsImmediatePropagationStopped() {
			break
		}

		// Keep once listeners removed.
		if !entry.Once {
			remaining = append(remaining, entry)
		}
	}
	le.entries = remaining
}

// funcPtrEqual compares two function values by their pointer identity.
func funcPtrEqual(a, b EventListener) bool {
	return reflect.ValueOf(a).Pointer() == reflect.ValueOf(b).Pointer()
}
